site_name: Enhanced Livestock
site_description: Guide and documentation for the Enhanced Livestock mod for Farming Simulator 25
site_url: https://renfordt.github.io/FS25_EnhancedLivestock

repo_url: https://github.com/renfordt/FS25_EnhancedLivestock
repo_name: FS25_EnhancedLivestock

docs_dir: docs

theme:
  name: material
  icon:
    logo: material/agriculture
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  features:
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - content.tooltips

plugins:
  - search
  - privacy

markdown_extensions:
  - admonition
  - tables
  - pymdownx.superfences

nav:
  - Home: index.md
  - Features:
      - Individual Animals: individual_animals.md
      - Genetics: genetics.md
      - Breeding: breeding.md
      - Diseases: disease.md
      - Productions: productions.md
      - Herdsman: herdsman.md
      - Message Log: message_log.md
      - Monitor: monitor.md
  - Animals:
      - Cattle: cattle.md
      - Pigs: pigs.md
      - Sheep: sheep.md
      - Goats: goats.md
      - Horses: horses.md
      - Chickens: chickens.md
  - Diseases:
      - Mastitis: mastitis.md
      - CVM: cvm.md
      - Foot and Mouth: foot_and_mouth.md
      - Porcine Epidemic Diarrhea: porcine_epidemic_diarrhea.md
      - Avian Influenza: avian_influenza.md
  - Compatibility: compatibility.md